version: '3.8'
services:
  web:
    build: .
    container_name: blockchain-web
    ports:
      - "5000:5000"
    environment:
      - USE_REDIS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./chain.json:/app/chain.json
  redis:
    image: redis:6
    container_name: blockchain-redis
    ports:
      - "6379:6379"